<a href="https://colab.research.google.com/github/alexmacharia/deep_learning_projects/blob/main/CNN_Cifar10_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

import keras
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.callbacks import ModelCheckpoint
from pathlib import Path

In [2]:
# Load the data

(x_train, y_train), (x_test, y_test) = cifar10.load_data()

print(x_train.shape)
print(x_test.shape)

print(y_train.shape)
print(y_test.shape)

170498071/170498071 [==============================] - 6s 0us/step
(50000, 32, 32, 3)
(10000, 32, 32, 3)
(50000, 1)
(10000, 1)


In [3]:
#Normalize data between 0 and 1
x_train = x_train.astype('float32')/255
x_test = x_test.astype('float32')/255

print(x_train[0])


[[[0.23137255 0.24313726 0.24705882]
  [0.16862746 0.18039216 0.1764706 ]
  [0.19607843 0.1882353  0.16862746]
  ...
  [0.61960787 0.5176471  0.42352942]
  [0.59607846 0.49019608 0.4       ]
  [0.5803922  0.4862745  0.40392157]]

 [[0.0627451  0.07843138 0.07843138]
  [0.         0.         0.        ]
  [0.07058824 0.03137255 0.        ]
  ...
  [0.48235294 0.34509805 0.21568628]
  [0.46666667 0.3254902  0.19607843]
  [0.47843137 0.34117648 0.22352941]]

 [[0.09803922 0.09411765 0.08235294]
  [0.0627451  0.02745098 0.        ]
  [0.19215687 0.10588235 0.03137255]
  ...
  [0.4627451  0.32941177 0.19607843]
  [0.47058824 0.32941177 0.19607843]
  [0.42745098 0.28627452 0.16470589]]

 ...

 [[0.8156863  0.6666667  0.3764706 ]
  [0.7882353  0.6        0.13333334]
  [0.7764706  0.6313726  0.10196079]
  ...
  [0.627451   0.52156866 0.27450982]
  [0.21960784 0.12156863 0.02745098]
  [0.20784314 0.13333334 0.07843138]]

 [[0.7058824  0.54509807 0.3764706 ]
  [0.6784314  0.48235294 0.16470589]


In [4]:
# Convert label to one hot
print(np.unique(y_train))

y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

print(y_train.shape)
print(y_test.shape)

[0 1 2 3 4 5 6 7 8 9]
(50000, 10)
(10000, 10)


In [5]:
# Create Sequential model

model = Sequential()

model.add(Conv2D(32, (3,3), padding="same", input_shape=(32, 32, 3), activation="relu"))
model.add(Conv2D(32, (3,3), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3,3), padding="same", activation="relu"))
model.add(Conv2D(64, (3,3), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512, activation="relu"))
model.add(Dropout(0.25))
model.add(Dense(10, activation="softmax"))

In [6]:
# Compile the model

model.compile(loss="categorical_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 32)        896       
                                                                 
 conv2d_1 (Conv2D)           (None, 30, 30, 32)        9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 15, 15, 32)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 15, 15, 32)        0         
                                                                 
 conv2d_2 (Conv2D)           (None, 15, 15, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 13, 13, 64)        36928     
                                                        

In [8]:
filepath="weights.best.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]

In [9]:
history = model.fit(x_train,
                    y_train,
                    batch_size=64,
                    epochs=30,
                    validation_split=0.2,
                    shuffle=True,
                    callbacks=callbacks_list
                    )

Epoch 1/30
625/625 [==============================] - ETA: 0s - loss: 1.5483 - accuracy: 0.4342
Epoch 1: val_accuracy improved from -inf to 0.56080, saving model to weights.best.hdf5
625/625 [==============================] - 227s 362ms/step - loss: 1.5483 - accuracy: 0.4342 - val_loss: 1.2233 - val_accuracy: 0.5608
Epoch 2/30
625/625 [==============================] - ETA: 0s - loss: 1.1672 - accuracy: 0.5853
Epoch 2: val_accuracy improved from 0.56080 to 0.62210, saving model to weights.best.hdf5
625/625 [==============================] - 229s 367ms/step - loss: 1.1672 - accuracy: 0.5853 - val_loss: 1.0665 - val_accuracy: 0.6221
Epoch 3/30
625/625 [==============================] - ETA: 0s - loss: 0.9718 - accuracy: 0.6576
Epoch 3: val_accuracy improved from 0.62210 to 0.69170, saving model to weights.best.hdf5
625/625 [==============================] - 243s 389ms/step - loss: 0.9718 - accuracy: 0.6576 - val_loss: 0.8689 - val_accuracy: 0.6917
Epoch 4/30
625/625 [====================

In [10]:
# Save the neural network structure

model_structure = model.to_json()
f = Path("model_structure.json")
f.write_text(model_structure)

4384

In [11]:
from keras.saving.model_config import model_from_json
# Load model structure

model_structure = f.read_text()

model_loaded = model_from_json(model_structure)

In [12]:
# Load weights

model_loaded.load_weights("weights.best.hdf5")